// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Mnemonic = 1,
  FlowMnemonic = 2,
  DirectiveName = 3,
  Program = 4,
  Label = 5,
  Statement = 6,
  Suffix = 7,
  Operand = 8,
  Absolute = 9,
  Areg = 10,
  Reg = 11,
  Dreg = 12,
  Directive = 13,
  DirectiveOperand = 14,
  String = 15,
  Comment = 16,
  CommentLine = 17
