import { ExternalTokenizer } from "@lezer/lr"
// Import the term IDs generated by lezer-generator
import { Mnemonic, DirectiveName, FlowMnemonic, Dreg, Areg} from "./parser.terms.js"
import {Label} from "./parser.terms.js"

const mnemonics = new Set([
    "abcd", "adda", "addi", "add", "addq", "addx", "andi", "and", "asl", "asr",
    "bchg", "bclr", "bfchg", "bfclr", "bfexts", "bfextu", "bfffo", "bfins", "bfset", "bftst", "bkpt", "bset", "btst",
    "callm", "cas2", "cas", "chk2", "chk", "cinva", "cinvl", "cinvp", "clr",
    "cmp2", "cmpa", "cmpi", "cmp", "cmpm", "cpusha", "cpushl", "cpushp",
    "divs", "divsl", "divu", "divul",
    "eori", "eor", "exg", "extb", "ext", "illegal",
    "lea", "link", "lpstop", "lsl", "lsr",
    "move16", "movea", "movec", "move", "movem", "movep", "moveq", "moves", "muls", "mulu",
    "nbcd", "neg", "negx", "nop", "not", "ori", "or",
    "pack", "pea", "pflusha", "pflushan", "pflush", "pflushn", "ploadr", "ploadw", "plpa", "pmovefd", "pmove", "ptestr", "ptestw",
    "reset", "rol", "ror", "roxl", "roxr",
    "sbcd", "scc", "scs", "seq", "sf", "sge", "sgt", "shi", "shs", "sle", "slo", "sls", "slt", "smi", "sne", "spl", "st", "stop",
    "suba", "subi", "sub", "subq", "subx", "svc", "svs", "swap",
    "tas", "tst",
    "unlk", "unpk",
    "fabs", "facos", "fadd", "fasin", "fatanh", "fatan", "fcmp", "fcosh", "fcos", "fdabs", "fdadd", "fddiv", "fdiv", "fdmove", "fdmul", "fdneg", "fdsqrt", "fdsub", "fetox", "fetoxm1", "fgetexp", "fgetman", "fint", "fintrz", "flog10", "flog2", "flogn", "flognp1", "fmod", "fmovecr", "fmove", "fmovem", "fmul", "fneg", "fnop", "frem", "frestore", "fsabs", "fsadd", "fsave", "fscale", "fsdiv", "fseq", "fsf", "fsge", "fsgldiv", "fsgle", "fsgl", "fsglmul", "fsgt", "fsincos", "fsinh", "fsin", "fsle", "fslt", "fsmove", "fsmul", "fsneg", "fsne", "fsnge", "fsngle", "fsngl", "fsngt", "fsnle", "fsnlt", "fsoge", "fsogl", "fsogt", "fsole", "fsolt", "fsor", "fsqrt", "fsseq", "fssf", "fssne", "fssqrt", "fsst", "fssub", "fst", "fsub", "fsueq", "fsuge", "fsugt", "fsule", "fsult", "fsun", "ftanh", "ftan", "ftentox", "ftst", "ftwotox"
]);

const flowMnemonics = new Set([
    "bcc", "bcs", "beq", "bge", "bgt", "bhi", "ble", "bls", "blt", "bmi", "bne", "bpl", "bvc", "bvs", "bra", "bsr", "bhs", "blo",
    "dbcc", "dbcs", "dbeq", "dbge", "dbgt", "dbhi", "dble", "dbls", "dblt", "dbmi", "dbne", "dbpl", "dbvc", "dbvs", "dbt", "dbf", "dbra", "dbhs", "dblo",
    "jmp", "jsr",
    "rts", "rtr", "rte", "rtd", "rtm",
    "trap", "trapv", "trapcc", "trapcs", "trapeq", "trapf", "trapge", "trapgt", "traphi", "traphs", "traple", "traplo", "trapls", "traplt", "trapmi", "trapne", "trappl", "trapt", "trapvc",
    "fbeq", "fbf", "fbge", "fbgle", "fbgl", "fbgt", "fble", "fblt", "fbne", "fbnge", "fbngle", "fbngl", "fbngt", "fbnle", "fbnlt", "fboge", "fbogl", "fbogt", "fbole", "fbolt", "fbor", "fbseq", "fbsf", "fbsne", "fbst", "fbt", "fbueq", "fbuge", "fbugt", "fbule", "fbult", "fbun",
    "fdbeq", "fdbf", "fdbge", "fdbgle", "fdbgl", "fdbgt", "fdble", "fdblt", "fdbne", "fdbnge", "fdbngle", "fdbngl", "fdbngt", "fdbnle", "fdbnlt", "fdboge", "fdbogl", "fdbogt", "fdbole", "fdbolt", "fdbor", "fdbseq", "fdbsf", "fdbsne", "fdbst", "fdbt", "fdbueq", "fdbuge", "fdbugt", "fdbule", "fdbult", "fdbun",
    "ftrapeq", "ftrapf", "ftrapge", "ftrapgle", "ftrapgl", "ftrapgt", "ftraple", "ftraplt", "ftrapne", "ftrapnge", "ftrapngle", "ftrapngl", "ftrapngt", "ftrapnle", "ftrapnlt", "ftrapoge", "ftrapogl", "ftrapogt", "ftrapole", "ftrapolt", "ftrapor", "ftrapseq", "ftrapsf", "ftrapsne", "ftrapst", "ftrapt", "ftrapueq", "ftrapuge", "ftrapugt", "ftrapule", "ftrapult", "ftrapun"
]);

const directives = new Set([
    "align", "blk", "bss", "clrfo", "clrso", "cnop", "code", "cseg", "data", "dc", "dcb", "ds", "dseg", "else", "end", "endc", "endif", "endm", "endr", "equ", "even", "fo", "idnt", "if", "ifeq", "ifne", "ifgt", "ifge", "iflt", "ifle", "ifd", "ifnd", "ifc", "ifnc", "incbin", "incdir", "include", "macro", "org", "public", "rept", "rs", "rsreset", "rsset", "section", "set", "setfo", "setso", "so", "text", "ttl", "xdef", "xref", "sdreg", "cpu32", "far", "fpu", "machine", "mc68000", "mc68010", "mc68020", "mc68030", "mc68040", "mc68060", "mcf5200", "mcf5206", "mcf5307", "mcf5407", "near", "opt", "equr", "equrl", "fequr", "fequrl", "freg", "reg", "debug"
  ]);

export const externalKeywords = new ExternalTokenizer((input, stack) => {
  // 1. Read the word
  let start = input.pos;
  let word = "";
  while (input.next >= 48 && input.next <= 57 || // 0-9
         input.next >= 65 && input.next <= 90 || // A-Z
         input.next >= 97 && input.next <= 122 || // a-z
         input.next == 95) { // _
    word += String.fromCharCode(input.next);
    input.advance();
  }

  if (word.length > 0) {
    let lower = word.toLowerCase();
    if (mnemonics.has(lower)) {
      input.acceptToken(Mnemonic);
    } 
    else if (flowMnemonics.has(lower)) {
      input.acceptToken(FlowMnemonic);
    }
    else if (directives.has(lower)) {
      input.acceptToken(DirectiveName);
    }
  }
});

export function regs(value) {
  let low = value.toLowerCase();
  if (/^d[0-7]$/.test(low) || low === "sr" || low === "ccr" || low === "vbr") return Dreg;
  if (/^a[0-7]$/.test(low) || ["sp", "pc", "usp", "ssp"].includes(low)) return Areg;
  return -1; // -1 means "keep as word"
}